[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true

[stackGroups]
	enableStackGroups = true
	disabledStackGroups = ["c:raw_materials", "minecraft:minecarts", "c:buckets", "computercraft:turtle_normal"]
