#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 31 10:21:02 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=ComplementaryReimagined_r5.7.1.zip
